### ISSUE TITLE
[1.0.4] breaking farmersdelight:cuttingboard somehow

### ISSUE THREAD

**Issue by abrossimow** [jflec/sellingbin#4]
# Description:
After installing Joe's Selling Bin (1.0.4) off Modrinth for a modpack, cutting with Farmer's Delight cutting board does not work properly anymore. With this mod, only tools with full durability are recognized as valid items for interaction.

This is not happening with the original release Selling Bin (1.6).

Running MC 1.20.1 with Fabric 0.16.7 and Farmer's Delight Refabricated 2.1.6

# Reproduction:
Install all mentioned mods. Place farmersdelight:cutting_board. Place item (i.e. minecraft:beef or farmersdelight:cabbage) on cutting board. Use famersdelight:flint_knife (or similar) to interact. First time works, as item has full durability. Repeat: breaks.

**Comment by abrossimow** [comment]
Is it possible that this has been fixed on a more recent release on curseforge already?

**Comment by jflec** [comment]
It has been fixed on CurseForge 1.0.9 is what you're looking for, will upload to Modrinth soon
