### ISSUE TITLE
Inventory not accessible by other systems

### ISSUE THREAD

**Issue by abrossimow** [jflec/sellingbin#6]
In general inventory containers are accessible by adjacent blocks for interaction. Look at chests and barrels in conjunction with hoppers for example.
It would be great to have that for the Selling Bin, too. Use cases could be for AE2, Tom's Simple Storage or even for Create's Funnels.

Without looking further into it, might be dependant on:
```
import net.minecraft.world.Container;
import net.minecraft.world.Containers;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.StateDefinition;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.world.level.block.state.properties.BooleanProperty;
import net.minecraft.world.level.block.state.properties.DirectionProperty;
```
and:
```
	@Override
	public boolean hasAnalogOutputSignal(BlockState state) {
		return true;
	}

	@Override
	public int getAnalogOutputSignal(BlockState blockState, Level level, BlockPos pos) {
		return AbstractContainerMenu.getRedstoneSignalFromBlockEntity(level.getBlockEntity(pos));
	}
```

**Comment by jflec** [comment]
Which version are you on? The new Redstone bin allows for input

**Comment by abrossimow** [comment]
Version is 1.0.9 - thanks! I did expect all bins to allow input, but restricting this to redstone is just a good idea :)

**Comment by abrossimow** [comment]
Version is 1.0.9 - thanks! I did expect all bins to allow input, but restricting this to redstone is just a good idea :)
